#!/bin/bash
available="/etc/nginx/sites-available/"
enabled="/etc/nginx/sites-enabled/"
if [ $# -eq 0 ]; then
	echo "No arguments supplied. Run the script with the name of a vhost file in the '${available}' directory"
	 exit
fi
site="$1"
if [ "$(ls -lh $available | grep "$site")" ]; then
	echo "INFO: found file '${available}${site}'"
	if [ "$(ls -lh $enabled | grep "$site")" ]; then
		echo "WARNING: Site '${enabled}${site}' is already enabled. Exiting!"
		exit
	else
		echo "INFO: file '${enabled}${site}' doesn't exist. Linking in now..."
		ln -s ${available}${site} ${enabled}
		if [ "$(ls -lh $enabled | grep "$site")" ]; then
			echo "INFO: link '${enabled}${site}' created successfully. Verifying nginx configuation..."
			nginx -t > /dev/null 2>&1
			if [ "$?" = "0" ]; then
				echo "INFO: nginx configuration verified. Restarting nginx.."
				service nginx restart
			else
				echo "WARNING: nginx configuration failed to verify. Refer to the following text for cause:"
				echo ""
				nginx -t
				exit
			fi
		else
			echo "INFO: link '${enabled}${site}' not created. Something went wrong. Exiting!"
			exit
		fi
	fi
else
	echo "WARNING: file '${available}${site}' doesn't exist. Exiting!"
	exit
fi
